language: python
dist: focal
cache: false
env:
env:
  global:
  - LANG="en_US.UTF-8" LC_ALL="en_US.UTF-8" LD_PRELOAD="/lib/x86_64-linux-gnu/libSegFault.so" SEGFAULT_SIGNALS="all"
matrix:
  include:
    - python: '3.8'
      env:
        - TOXENV=check
    - python: '3.8'
      env:
        - TOXENV=docs
    - env:
        - TOXENV=py36
      python: '3.6'
    - env:
        - TOXENV=py37
      python: '3.7'
    - env:
        - TOXENV=py38
      python: '3.8'
before_install:
  - python -V
  - uname -a
  - lsb_release -a || true
install:
  - python -mpip install -U pip
  - python -mpip install --progress-bar=off -U tox flake8 pytest pytest-cov coverage pytest-travis-fold check-manifest elasticmock elasticsearch
  - virtualenv --version
  - easy_install --version
  - python -mpip --version
  - tox --version
before_script: cd python/datamonitor
script:
  - tox -v 
after_failure:
  - more .tox/log/* | cat
  - more .tox/*/log/* | cat
notifications:
  email:
    on_success: never
    on_failure: always

